---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # the name of the check-vault role binding
  name: check-vault
subjects:
  - kind: ServiceAccount
    name: check-vault
    # the namespace where the check vault pod is deployed. preferably same namespace as Vault instance
    namespace: tm-deploy-ns
roleRef:
  kind: ClusterRole
  name: check-vault
  apiGroup: rbac.authorization.k8s.io
