---
# ClusterRole required by check vault to be able to get the necessary resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: check-vault
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - cronjobs
  - jobs
  - namespaces
  - nodes
  - pods
  - services
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
