---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-istio
  # the namespace where the Vault Installer pod is deployed to
  namespace: 'tm-deploy-ns'
# this should be uncommented if a private repo is used
#imagePullSecrets:
#  - name: {IMAGE_PULL_SECRETS_NAME}
