---
apiVersion: v1
kind: ServiceAccount
metadata:
  # service account name. should be the same service account which the vault-installer HashiCorp Vault role
  # is set to for successful vault-installer pod and HashiCorp Vault authentication
  name: 'vault-sa'
  # the namespace where the Vault Installer pod is deployed to
  namespace: 'tm-deploy-ns'
# this should be uncommented if a private repo is used
#imagePullSecrets:
#  - name: {IMAGE_PULL_SECRETS_NAME}
